<?php
/**
 * Template Name: Diætist Danmark — Portal for Autoriseret Klinisk Diætbehandling
 * Description: Generated by Variated AI Designer
 */
?><!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
  <meta charset="<?php bloginfo('charset'); ?>">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <?php wp_head(); ?>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=Plus+Jakarta+Sans:wght@300;400;500;600;700&display=swap"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"/>

  <link rel="stylesheet" href="<?php echo esc_url(get_stylesheet_directory_uri() . '/variated/di-tist-danmark-portal-for-autoriseret-klinisk-di-tbehandling/style.css'); ?>">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js"></script>

</head>
<body <?php body_class('variated-export-page variated-export-page--di-tist-danmark-portal-for-autoriseret-klinisk-di-tbehandling'); ?>>
  <div class="variated-export variated-export--di-tist-danmark-portal-for-autoriseret-klinisk-di-tbehandling">
<!-- HEADER -->
  <header data-block-id="block-01-header">
    <div class="container nav-container">
      <a href="#" class="logo">
        <img class="dd-brand-logo" alt="Diætist Danmark" />
      </a>
      <nav class="nav-links" data-block-id="block-02-nav">
        <a href="#specialiteter" class="nav-link">Specialer</a>
        <a href="#find-diaetist" class="nav-link">Find Diætist</a>
        <a href="#tilskud" class="nav-link">Tilskud</a>
        <a href="#foredrag" class="nav-link">Foredrag &amp; Erhverv</a>
        <a href="#viden" class="nav-link">Viden</a>
        <a href="#find-diaetist" class="btn btn-secondary">Find behandler</a>
      </nav>
      <button class="menu-toggle" id="menu-toggle" type="button" aria-label="Åbn menu">
        <span></span>
        <span></span>
        <span></span>
      </button>
    </div>
  </header>

  <div class="mobile-nav" id="mobile-nav" aria-hidden="true">
    <a href="#specialiteter">Specialer</a>
    <a href="#find-diaetist">Find Diætist</a>
    <a href="#tilskud">Tilskud</a>
    <a href="#foredrag">Foredrag &amp; Erhverv</a>
    <a href="#viden">Viden</a>
    <a href="#find-diaetist" class="btn btn-secondary">Find behandler</a>
  </div>

  <main data-block-id="block-03-main">
    
    <!-- HERO SECTION -->
    <section class="container hero-section" data-block-id="block-04-section">
      <div class="hero-content">
        <div class="hero-tagline">Autoriserede kliniske diætister</div>
        <h1 class="hero-title">Videnskabeligt funderet ernæring. Formidlet med nærvær.</h1>
        <p class="hero-description">
          Vi forbinder private, virksomheder og organisationer med landets førende sundhedsfaglige eksperter. Ingen quick-fixes — kun evidensbaseret vejledning skræddersyet til dit liv og dit helbred.
        </p>
        
        <!-- Quick Finder Widget -->
        <div class="hero-finder">
          <div class="finder-field">
            <label for="hero-region">Region</label>
            <select id="hero-region">
              <option value="alle">Hele Danmark</option>
              <option value="hovedstaden">Hovedstaden</option>
              <option value="sjaelland">Sjælland</option>
              <option value="syddanmark">Syddanmark</option>
              <option value="midtjylland">Midtjylland</option>
              <option value="nordjylland">Nordjylland</option>
            </select>
          </div>
          <div class="finder-field">
            <label for="hero-specialty">Speciale</label>
            <select id="hero-specialty">
              <option value="alle">Alle specialer</option>
              <option value="gastro">Gastrointestinale lidelser</option>
              <option value="kardio">Kardiovaskulær sundhed</option>
              <option value="diabetes">Diabetes &amp; Endokrinologi</option>
              <option value="spiseforstyrrelse">Spiseforstyrrelser</option>
            </select>
          </div>
          <button class="btn btn-primary" id="hero-search-btn" style="align-self: flex-end; height: 44px;">
            Søg nu <i class="fa-solid fa-arrow-right" style="margin-left: 0.5rem;"></i>
          </button>
        </div>
      </div>

      <!-- Right Side Editorial Card -->
      <div class="hero-graphic">
        <div class="clinical-seal">AUTORISERET<br>AF SUNDHEDS-<br>STYRELSEN</div>
        <div class="metric-block">
          <div class="metric-value" id="count-members">240+</div>
          <div class="metric-label">Aktive kliniske diætister fordelt over hele landet</div>
        </div>
        <div class="metric-block" style="border-top: 1px solid var(--border-line); padding-top: 1.5rem;">
          <div class="metric-value" id="count-consultations">15k+</div>
          <div class="metric-label">Årlige sundhedsfaglige konsultationer</div>
        </div>
        <p style="font-size: 0.9rem; opacity: 0.8; font-style: italic;">
          "Vores mission er at sikre, at alle danskere har adgang til kvalificeret og videnskabelig ernæringsrådgivning."
        </p>
      </div>
    </section>

    <!-- MODULAR SPECIALTIES (10 categories) -->
    <section id="specialiteter" class="container section-pad-lg" data-block-id="block-05-section">
      <div class="section-header">
        <span class="section-subtitle">Kliniske kernekompetencer</span>
        <h2 class="section-title">Hvad kan en klinisk diætist hjælpe med?</h2>
        <p style="max-width: 600px; text-align: center; margin-top: 0.5rem;">
          Vores medlemmer er autoriserede sundhedspersoner med en professionsbachelor i ernæring og sundhed. De er uddannet til at yde diætbehandling ved sygdom og forebyggelse.
        </p>
      </div>

      <div class="specialties-grid">
        <!-- Card 1 -->
        <div class="specialty-card" data-specialty="gastro">
          <svg class="specialty-icon" viewBox="0 0 24 24">
            <path d="M12,2C11.5,2 10.1,4.4 9.5,6C8.8,7.6 8.5,9.5 8.5,11C8.5,14 10.1,15.5 12,15.5C13.9,15.5 15.5,14 15.5,11C15.5,9.5 15.2,7.6 14.5,6C13.9,4.4 12.5,2 12,2Z"></path>
            <path d="M12,15.5C9.5,15.5 7.5,17.5 7.5,20C7.5,21.1 8.4,22 9.5,22C10.6,22 11.5,21.1 11.5,20C11.5,19.4 12,19 12.5,19C13,19 13.5,19.4 13.5,20C13.5,21.1 14.4,22 15.5,22C16.6,22 17.5,21.1 17.5,20C17.5,17.5 15.5,15.5 12,15.5Z"></path>
          </svg>
          <h3 class="specialty-title">Gastrointestinale lidelser</h3>
          <p class="specialty-desc">Behandling og lindring af IBS (Irritabel tyktarm), colitis ulcerosa, Crohns sygdom og cøliaki.</p>
        </div>

        <!-- Card 2 -->
        <div class="specialty-card" data-specialty="kardio">
          <svg class="specialty-icon" viewBox="0 0 24 24">
            <path d="M12,21.35L10.55,20.03C5.4,15.36 2,12.27 2,8.5C2,5.41 4.42,3 7.5,3C9.24,3 10.91,3.81 12,5.08C13.09,3.81 14.76,3 16.5,3C19.58,3 22,5.41 22,8.5C22,12.27 18.6,15.36 13.45,20.03L12,21.35Z"></path>
          </svg>
          <h3 class="specialty-title">Kardiovaskulær sundhed</h3>
          <p class="specialty-desc">Koststrategier til sænkning af kolesterol, regulering af blodtryk samt forebyggelse af hjerte-kar-sygdomme.</p>
        </div>

        <!-- Card 3 -->
        <div class="specialty-card" data-specialty="diabetes">
          <svg class="specialty-icon" viewBox="0 0 24 24">
            <path d="M19,3H5C3.89,3 3,3.9 3,5V19C3,20.1 3.89,21 5,21H19C20.1,21 21,20.1 21,19V5C21,3.9 20.1,3 19,3M16,10.5H13.5V13H16V14.5H13.5V17H12V14.5H9.5V13H12V10.5H9.5V9H12V6.5H13.5V9H16V10.5Z"></path>
          </svg>
          <h3 class="specialty-title">Diabetes &amp; Endokrinologi</h3>
          <p class="specialty-desc">Regulering af blodsukker ved Type 1 og Type 2 diabetes, samt hormonelle ubalancer som PCOS.</p>
        </div>

        <!-- Card 4 -->
        <div class="specialty-card">
          <svg class="specialty-icon" viewBox="0 0 24 24">
            <path d="M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,4A8,8 0 0,1 20,12A8,8 0 0,1 12,20A8,8 0 0,1 4,12A8,8 0 0,1 12,4M12,6A6,6 0 0,0 6,12A6,6 0 0,0 12,18A6,6 0 0,0 18,12A6,6 0 0,0 12,6M12,8A4,4 0 0,1 16,12A4,4 0 0,1 12,16A4,4 0 0,1 8,12A4,4 0 0,1 12,8Z"></path>
          </svg>
          <h3 class="specialty-title">Børn &amp; Unge</h3>
          <p class="specialty-desc">Sikring af optimal vækst, håndtering af fødevareallergier og selektiv spiseadfærd hos børn.</p>
        </div>

        <!-- Card 5 -->
        <div class="specialty-card">
          <svg class="specialty-icon" viewBox="0 0 24 24">
            <path d="M12,3C7.03,3 3,7.03 3,12C3,16.97 7.03,21 12,21C16.97,21 21,16.97 21,12C21,7.03 16.97,3 12,3M12,18C8.69,18 6,15.31 6,12C6,8.69 8.69,6 12,6C15.31,6 18,8.69 18,12C18,15.31 15.31,18 12,18Z"></path>
          </svg>
          <h3 class="specialty-title">Ældre &amp; Geriatri</h3>
          <p class="specialty-desc">Ernæringsindsatser mod uplanlagt vægttab, dysfagi (synkebesvær) og genopbygning af muskelmasse.</p>
        </div>

        <!-- Card 6 -->
        <div class="specialty-card">
          <svg class="specialty-icon" viewBox="0 0 24 24">
            <path d="M12,2C11.5,2 10.1,4.4 9.5,6C8.8,7.6 8.5,9.5 8.5,11C8.5,14 10.1,15.5 12,15.5C13.9,15.5 15.5,14 15.5,11C15.5,9.5 15.2,7.6 14.5,6C13.9,4.4 12.5,2 12,2Z"></path>
          </svg>
          <h3 class="specialty-title">Sportsernæring</h3>
          <p class="specialty-desc">Optimering af energiindtag, væskebalance og restitution for både eliteudøvere og motionister.</p>
        </div>

        <!-- Card 7 -->
        <div class="specialty-card">
          <svg class="specialty-icon" viewBox="0 0 24 24">
            <path d="M12,3A9,9 0 0,0 3,12A9,9 0 0,0 12,21A9,9 0 0,0 21,12A9,9 0 0,0 12,3M12,5A7,7 0 0,1 19,12A7,7 0 0,1 12,19A7,7 0 0,1 5,12A7,7 0 0,1 12,5Z"></path>
          </svg>
          <h3 class="specialty-title">Onkologisk støtte</h3>
          <p class="specialty-desc">Ernæring under og efter kræftforløb for at opretholde styrke, vægt og lindre bivirkninger ved behandling.</p>
        </div>

        <!-- Card 8 -->
        <div class="specialty-card" data-specialty="spiseforstyrrelse">
          <svg class="specialty-icon" viewBox="0 0 24 24">
            <path d="M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,4A8,8 0 0,1 20,12A8,8 0 0,1 12,20A8,8 0 0,1 4,12A8,8 0 0,1 12,4Z"></path>
          </svg>
          <h3 class="specialty-title">Spiseforstyrrelser</h3>
          <p class="specialty-desc">Sensitiv og tværfaglig behandling af anoreksi, bulimi, BED (tvangsoverspisning) og ortoreksi.</p>
        </div>

        <!-- Card 9 -->
        <div class="specialty-card">
          <svg class="specialty-icon" viewBox="0 0 24 24">
            <path d="M12,2C6.48,2 2,6.48 2,12C2,17.52 6.48,22 12,22C17.52,22 22,17.52 22,12C22,6.48 17.52,2 12,2ZM12,20C7.59,20 4,16.41 4,12C4,7.59 7.59,4 12,4C16.41,4 20,7.59 20,12C20,16.41 16.41,20 12,20Z"></path>
          </svg>
          <h3 class="specialty-title">Allergier &amp; Intolerance</h3>
          <p class="specialty-desc">Sikker diagnosticering og navigering i en hverdag med laktoseintolerance, cøliaki eller histaminfølsomhed.</p>
        </div>

        <!-- Card 10 -->
        <div class="specialty-card">
          <svg class="specialty-icon" viewBox="0 0 24 24">
            <path d="M12,2C11.5,2 10.1,4.4 9.5,6C8.8,7.6 8.5,9.5 8.5,11C8.5,14 10.1,15.5 12,15.5C13.9,15.5 15.5,14 15.5,11C15.5,9.5 15.2,7.6 14.5,6C13.9,4.4 12.5,2 12,2Z"></path>
          </svg>
          <h3 class="specialty-title">Fertilitet &amp; Graviditet</h3>
          <p class="specialty-desc">Ernæringsoptimering før undfangelse, under graviditet og efter fødslen for mor og barn.</p>
        </div>
      </div>
    </section>

    <!-- INTERACTIVE FINDER (Map + Realtime list search) -->
    <section id="find-diaetist" class="finder-section" data-block-id="block-06-section">
      <div class="container">
        <div class="section-header">
          <span class="section-subtitle">Landsdækkende netværk</span>
          <h2 class="section-title">Find en autoriseret diætist nær dig</h2>
          <p style="max-width: 650px; text-align: center;">
            Klik direkte på kortet for at filtrere efter din region, eller vælg et speciale for at indsnævre din søgning øjeblikkeligt.
          </p>
        </div>

        <div class="finder-layout">
          <!-- Left: Interactive Denmark Map -->
          <div class="map-container">
            <!-- Inline SVG Denmark Map with high responsive visual targets -->
            <svg class="denmark-map" viewBox="0 0 600 500" xmlns="http://www.w3.org/2000/svg">
              <!-- Nordjylland -->
              <path class="map-region" id="region-nordjylland" data-region="nordjylland" d="M 180,20 L 250,15 L 340,50 L 320,110 L 280,120 L 230,140 L 190,130 L 170,90 Z"></path>
              <!-- Midtjylland -->
              <path class="map-region" id="region-midtjylland" data-region="midtjylland" d="M 170,140 L 230,140 L 280,125 L 330,115 L 350,160 L 320,240 L 160,250 L 130,190 Z"></path>
              <!-- Syddanmark -->
              <path class="map-region" id="region-syddanmark" data-region="syddanmark" d="M 160,250 L 320,240 L 300,320 L 260,370 L 160,370 L 140,310 Z"></path>
              <!-- Sjælland -->
              <path class="map-region" id="region-sjaelland" data-region="sjaelland" d="M 400,220 L 480,220 L 490,290 L 410,340 L 360,300 L 370,250 Z"></path>
              <!-- Hovedstaden -->
              <path class="map-region" id="region-hovedstaden" data-region="hovedstaden" d="M 480,220 L 530,180 L 550,220 L 510,260 Z"></path>
            </svg>

            <!-- Quick Region Selector Buttons -->
            <div class="region-legend">
              <button class="region-btn active" data-region="alle">Hele landet</button>
              <button class="region-btn" data-region="hovedstaden">Hovedstaden</button>
              <button class="region-btn" data-region="sjaelland">Sjælland</button>
              <button class="region-btn" data-region="syddanmark">Syddanmark</button>
              <button class="region-btn" data-region="midtjylland">Midtjylland</button>
              <button class="region-btn" data-region="nordjylland">Nordjylland</button>
            </div>
          </div>

          <!-- Right: Interactive results list -->
          <div class="results-container">
            <div class="results-header">
              <h3 class="results-title">Behandlere i <span id="current-region-text">Hele landet</span></h3>
              <span class="results-count" id="results-count-badge">5 fundet</span>
            </div>

            <!-- Dietitian List -->
            <div class="dietitian-list" id="dietitian-list">
              <!-- Item 1 -->
              <div class="dietitian-card" data-regions="hovedstaden" data-specs="gastro diabetes">
                <img src="https://picsum.photos/seed/doc1/120/120" alt="Mette Poulsen" class="dietitian-avatar">
                <div class="dietitian-info">
                  <h4 style="font-size: 1.2rem; color: var(--border-line);">Mette Poulsen</h4>
                  <p style="font-size: 0.85rem; font-weight: 600; opacity: 0.8;">København Ø &amp; Online</p>
                  <p style="font-size: 0.85rem; line-height: 1.4;">Specialist i irritabel tyktarm (IBS), low FODMAP diæt samt type 2 diabetes.</p>
                  <div class="dietitian-meta">
                    <span class="tag">Hovedstaden</span>
                    <span class="tag tag-blue">Gastro</span>
                    <span class="tag tag-blue">Diabetes</span>
                  </div>
                </div>
              </div>

              <!-- Item 2 -->
              <div class="dietitian-card" data-regions="midtjylland" data-specs="kardio diabetes">
                <img src="https://picsum.photos/seed/doc2/120/120" alt="Henrik Nielsen" class="dietitian-avatar">
                <div class="dietitian-info">
                  <h4 style="font-size: 1.2rem; color: var(--border-line);">Henrik Nielsen</h4>
                  <p style="font-size: 0.85rem; font-weight: 600; opacity: 0.8;">Aarhus C</p>
                  <p style="font-size: 0.85rem; line-height: 1.4;">Fokus på forebyggelse af hjerte-kar-sygdomme og optimering af kolesteroltal.</p>
                  <div class="dietitian-meta">
                    <span class="tag">Midtjylland</span>
                    <span class="tag tag-blue">Kardio</span>
                    <span class="tag tag-blue">Diabetes</span>
                  </div>
                </div>
              </div>

              <!-- Item 3 -->
              <div class="dietitian-card" data-regions="syddanmark" data-specs="spiseforstyrrelse">
                <img src="https://picsum.photos/seed/doc3/120/120" alt="Signe Kragh" class="dietitian-avatar">
                <div class="dietitian-info">
                  <h4 style="font-size: 1.2rem; color: var(--border-line);">Signe Kragh</h4>
                  <p style="font-size: 0.85rem; font-weight: 600; opacity: 0.8;">Odense M &amp; Svendborg</p>
                  <p style="font-size: 0.85rem; line-height: 1.4;">Mangeårig erfaring med behandling af spiseforstyrrelser og overspisning (BED).</p>
                  <div class="dietitian-meta">
                    <span class="tag">Syddanmark</span>
                    <span class="tag tag-blue">Spiseforstyrrelse</span>
                  </div>
                </div>
              </div>

              <!-- Item 4 -->
              <div class="dietitian-card" data-regions="nordjylland" data-specs="gastro">
                <img src="https://picsum.photos/seed/doc4/120/120" alt="Anette Schmidt" class="dietitian-avatar">
                <div class="dietitian-info">
                  <h4 style="font-size: 1.2rem; color: var(--border-line);">Anette Schmidt</h4>
                  <p style="font-size: 0.85rem; font-weight: 600; opacity: 0.8;">Aalborg</p>
                  <p style="font-size: 0.85rem; line-height: 1.4;">Individuelle forløb til mave-tarm-udfordringer samt inflammatoriske tarmsygdomme.</p>
                  <div class="dietitian-meta">
                    <span class="tag">Nordjylland</span>
                    <span class="tag tag-blue">Gastro</span>
                  </div>
                </div>
              </div>

              <!-- Item 5 -->
              <div class="dietitian-card" data-regions="sjaelland" data-specs="diabetes kardio">
                <img src="https://picsum.photos/seed/doc5/120/120" alt="Christian Lind" class="dietitian-avatar">
                <div class="dietitian-info">
                  <h4 style="font-size: 1.2rem; color: var(--border-line);">Christian Lind</h4>
                  <p style="font-size: 0.85rem; font-weight: 600; opacity: 0.8;">Roskilde</p>
                  <p style="font-size: 0.85rem; line-height: 1.4;">Klinisk diætbehandling med vægt på livsstilsændringer ved metaboliske udfordringer.</p>
                  <div class="dietitian-meta">
                    <span class="tag">Sjælland</span>
                    <span class="tag tag-blue">Diabetes</span>
                    <span class="tag tag-blue">Kardio</span>
                  </div>
                </div>
              </div>
            </div>

            <!-- Live Search Actions -->
            <div style="border-top: 1px solid var(--border-line); padding-top: 1rem; display: flex; justify-content: space-between; align-items: center;">
              <span style="font-size: 0.85rem; opacity: 0.7;">Alle behandlere er statsautoriserede.</span>
              <a href="#" class="btn btn-primary btn-sm" style="padding: 0.5rem 1rem; font-size: 0.8rem;">Book direkte</a>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- SUBSIDIES (TILSKUD) SECTION -->
    <section id="tilskud" class="subsidies-section container" data-block-id="block-07-section">
      <div class="section-header">
        <span class="section-subtitle">Finansiering &amp; Tilskud</span>
        <h2 class="section-title">Muligheder for økonomisk støtte</h2>
        <p style="max-width: 600px;">
          Klinisk diætbehandling er anerkendt af det offentlige sundhedsvæsen, hvilket giver gode muligheder for tilskud til dine konsultationer.
        </p>
      </div>

      <div class="subsidies-grid">
        <!-- Card 1 -->
        <div class="subsidy-card">
          <span class="subsidy-label">Sygeforsikringen "danmark"</span>
          <h3 class="subsidy-title">Op til 50% refunderet</h3>
          <p>
            Er du medlem af Sygeforsikringen "danmark" i gruppe 1, 2 eller 5, kan du modtage væsentligt tilskud til dine konsultationer hos en autoriseret klinisk diætist.
          </p>
          <div class="subsidy-points">
            <div class="subsidy-point">
              <i class="fa-solid fa-circle-check"></i>
              <div>
                <strong>Nem indberetning:</strong> Diætisten indberetter typisk elektronisk direkte til "danmark" efter din konsultation.
              </div>
            </div>
            <div class="subsidy-point">
              <i class="fa-solid fa-circle-check"></i>
              <div>
                <strong>Ingen lægehenvisning påkrævet:</strong> Du kan søge og få tilskud uden forudgående henvisning fra egen læge.
              </div>
            </div>
          </div>
        </div>

        <!-- Card 2 -->
        <div class="subsidy-card blue">
          <span class="subsidy-label">Offentlig Lægehenvisning</span>
          <h3 class="subsidy-title">Henvisning fra egen læge</h3>
          <p>
            Har du en kronisk sygdom såsom type 2-diabetes, svær KOL eller hjerte-kar-sygdom, kan din læge udstede en henvisning til diætbehandling.
          </p>
          <div class="subsidy-points">
            <div class="subsidy-point">
              <i class="fa-solid fa-circle-check"></i>
              <div>
                <strong>Kommunale tilbud:</strong> Mange kommuner tilbyder gratis forløb hos en klinisk diætist via sundhedscentre.
              </div>
            </div>
            <div class="subsidy-point">
              <i class="fa-solid fa-circle-check"></i>
              <div>
                <strong>Sundhedsfaglige kriterier:</strong> Din læge vurderer, om du opfylder kriterierne for en målrettet ernæringsindsats.
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- CONSULTANCY & SPEAKING (FOREDRAG) -->
    <section id="foredrag" class="foredrag-section" data-block-id="block-08-section">
      <div class="container foredrag-grid">
        <div class="foredrag-content">
          <span class="section-subtitle" style="color: var(--interactive-sand);">B2B &amp; Organisationer</span>
          <h2 class="hero-title">Foredrag &amp; Virksomhedsaftaler</h2>
          <p class="hero-description">
            Skab en sundere arbejdsplads baseret på reel viden frem for myter. Vi tilbyder skræddersyede foredrag, workshops og individuelle sundhedsforløb tilpasset din virksomheds behov.
          </p>
          
          <div class="foredrag-features">
            <div class="foredrag-feature">
              <h4 class="foredrag-feature-title"><i class="fa-solid fa-chalkboard-user" style="color: var(--interactive-sand); margin-right: 0.5rem;"></i> Evidensbaserede foredrag</h4>
              <p style="font-size: 0.9rem; opacity: 0.8;">Aktuelle emner som mave-tarm-sundhed, energi i hverdagen og stressforebyggelse.</p>
            </div>
            <div class="foredrag-feature">
              <h4 class="foredrag-feature-title"><i class="fa-solid fa-briefcase" style="color: var(--interactive-sand); margin-right: 0.5rem;"></i> Sundhedstjek på jobbet</h4>
              <p style="font-size: 0.9rem; opacity: 0.8;">Individuelle målinger, kropsanalyser og målorienteret sparring på arbejdspladsen.</p>
            </div>
          </div>

          <div style="margin-top: 1rem;">
            <a href="#" class="btn btn-secondary" style="border-color: var(--base-canvas); color: var(--base-canvas);">Book uforpligtende samtale</a>
          </div>
        </div>

        <div class="foredrag-showcase">
          <h3 style="font-family: var(--font-serif); font-size: 1.8rem; margin-bottom: 1.5rem; color: var(--interactive-sand);">Tidligere samarbejdspartnere</h3>
          <p style="font-size: 0.95rem; line-height: 1.6; opacity: 0.9; margin-bottom: 2rem;">
            Vi samarbejder med både offentlige instanser, kommuner og større private virksomheder om at højne sundheden og trivslen gennem faglig formidling.
          </p>
          <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 1.5rem; border-top: 1px solid rgba(245, 241, 235, 0.2); padding-top: 1.5rem;">
            <div>
              <strong style="display: block; font-size: 1.1rem; color: var(--base-canvas);">100+ afholdte workshops</strong>
              <span style="font-size: 0.8rem; opacity: 0.7;">Over hele landet i 2023</span>
            </div>
            <div>
              <strong style="display: block; font-size: 1.1rem; color: var(--base-canvas);">98% tilfredshed</strong>
              <span style="font-size: 0.8rem; opacity: 0.7;">Blandt deltagere og arrangører</span>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- KNOWLEDGE & FAQ SECTION -->
    <section id="viden" class="knowledge-section container" data-block-id="block-09-section">
      <div class="knowledge-grid">
        <!-- Left column: Latest news -->
        <div class="news-stack">
          <span class="section-subtitle">Nyeste viden</span>
          <h2 class="section-title">Evidensbaserede artikler</h2>
          <p style="margin-bottom: 1.5rem;">Vores diætister skriver løbende om ny forskning, opskrifter og praktiske råd til hverdagen.</p>
          
          <!-- Article 1 -->
          <article class="news-card" data-block-id="block-10-article">
            <span class="news-meta">April 2024 • Gastrointestinalt</span>
            <a href="#"><h3 class="news-title">IBS og Low-FODMAP: En guide til at genskabe roen i din mave</h3></a>
            <p style="font-size: 0.9rem; opacity: 0.8;">Få overblikket over faserne i low-FODMAP diæten, og lær hvordan du genintroducerer fødevarer uden unødigt ubehag.</p>
          </article>

          <!-- Article 2 -->
          <article class="news-card" data-block-id="block-11-article">
            <span class="news-meta">Marts 2024 • Diabetes</span>
            <a href="#"><h3 class="news-title">Stabiliser dit blodsukker med den rette måltidssammensætning</h3></a>
            <p style="font-size: 0.9rem; opacity: 0.8;">Hvorfor kulhydrater ikke skal frygtes, men blot kombineres rigtigt med proteiner og sunde fedtkilder.</p>
          </article>
        </div>

        <!-- Right column: FAQ Accordion -->
        <div style="display: flex; flex-direction: column; gap: 2rem;">
          <div>
            <span class="section-subtitle">Ofte stillede spørgsmål</span>
            <h2 class="section-title" style="margin-bottom: 1rem;">Få svar på dine spørgsmål</h2>
            <p>Har du spørgsmål til henvisninger, priser eller valg af diætist? Find de hyppigste svar her.</p>
          </div>

          <div class="faq-container">
            <div class="faq-item">
              <button class="faq-trigger">
                <span>Hvad er forskellen på en diætist og en kostvejleder?</span>
                <i class="fa-solid fa-plus faq-icon"></i>
              </button>
              <div class="faq-content">
                <p style="font-size: 0.95rem; opacity: 0.9;">
                  Klinisk diætist er en beskyttet titel, der kræver en 3½-årig statsautoriseret professionsbacheloruddannelse under Sundhedsministeriet. Kostvejledere har typisk kortere, private kurser og må ikke varetage diætbehandling ved sygdom.
                </p>
              </div>
            </div>

            <div class="faq-item">
              <button class="faq-trigger">
                <span>Kan jeg få tilskud fra det offentlige?</span>
                <i class="fa-solid fa-plus faq-icon"></i>
              </button>
              <div class="faq-content">
                <p style="font-size: 0.95rem; opacity: 0.9;">
                  Ja, hvis du har en lægehenvisning til f.eks. type 2-diabetes eller KOL, kan du ofte få gratis behandling i din kommunes sundhedscenter eller tilskud til privat behandling.
                </p>
              </div>
            </div>

            <div class="faq-item">
              <button class="faq-trigger">
                <span>Hvor mange konsultationer skal jeg regne med?</span>
                <i class="fa-solid fa-plus faq-icon"></i>
              </button>
              <div class="faq-content">
                <p style="font-size: 0.95rem; opacity: 0.9;">
                  Det varierer efter behov, men de fleste har gavn af et opstartsforløb bestående af en indledende samtale (60 min) og 2-4 opfølgende konsultationer (30-45 min) til justering og opfølgning.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

  </main>

  <!-- FOOTER -->
  <footer data-block-id="block-12-footer">
    <div class="container footer-grid">
      <div class="footer-col">
        <a href="#" class="logo">
          <img class="dd-brand-logo" alt="Diætist Danmark" />
        </a>
        <p style="font-size: 0.9rem; opacity: 0.8;">
          Landsdækkende portal for formidling af autoriseret klinisk diætbehandling til private og erhverv.
        </p>
      </div>
      <div class="footer-col">
        <h4 class="footer-title">Navigation</h4>
        <div class="footer-links">
          <a href="#specialiteter" class="footer-link">Særlige fagområder</a>
          <a href="#find-diaetist" class="footer-link">Søg efter diætist</a>
          <a href="#tilskud" class="footer-link">Tilskudsmuligheder</a>
          <a href="#foredrag" class="footer-link">Erhvervsaftaler</a>
        </div>
      </div>
      <div class="footer-col">
        <h4 class="footer-title">For behandlere</h4>
        <div class="footer-links">
          <a href="#" class="footer-link">Bliv en del af portalen</a>
          <a href="#" class="footer-link">Faglige retningslinjer</a>
          <a href="#" class="footer-link">Intranet &amp; Log-ind</a>
          <a href="#" class="footer-link">Vilkår &amp; Betingelser</a>
        </div>
      </div>
      <div class="footer-col">
        <h4 class="footer-title">Kontakt</h4>
        <p style="font-size: 0.9rem; opacity: 0.8;">
          Diætist Danmark AmbA<br>
          Nørre Voldgade 12, 1.<br>
          1358 København K<br>
          CVR: 98765432
        </p>
      </div>
    </div>
    <div class="container footer-bottom">
      <p>© 2024 Diætist Danmark. Alle rettigheder forbeholdes. Autoriserede behandlere kontrolleres via Styrelsen for Patientsikkerhed.</p>
      <div style="display: flex; gap: 1.5rem;">
        <a href="#" style="opacity: 0.8;"><i class="fa-brands fa-linkedin fa-lg"></i></a>
        <a href="#" style="opacity: 0.8;"><i class="fa-brands fa-facebook fa-lg"></i></a>
      </div>
    </div>
  </footer>

  <!-- Script for interactivity and smooth springs -->
</div>
  <?php wp_footer(); ?>
</body>
</html>
