<?php
/**
 * Template Name: Diætist Danmark | Autorisede kliniske diætister
 * Description: Generated by Variated AI Designer
 */
?><!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
  <meta charset="<?php bloginfo('charset'); ?>">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <?php wp_head(); ?>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,300..900;1,9..144,300..900&family=Plus+Jakarta+Sans:wght@300;400;500;600;700&display=swap"/>

  <link rel="stylesheet" href="<?php echo esc_url(get_stylesheet_directory_uri() . '/variated/di-tist-danmark-autorisede-kliniske-di-tister/style.css'); ?>">
    <script src="https://unpkg.com/lucide@latest"></script>

</head>
<body <?php body_class('variated-export-page variated-export-page--di-tist-danmark-autorisede-kliniske-di-tister'); ?>>
  <div class="variated-export variated-export--di-tist-danmark-autorisede-kliniske-di-tister">
<!-- Tactile Noise Texture Overlay -->
    <div class="noise-overlay"></div>

    <!-- Header Navigation -->
    <header data-block-id="block-01-header">
        <div class="container nav-wrapper">
            <a href="#" class="logo">
                <img class="dd-brand-logo" alt="Diætist Danmark" />
            </a>
            <nav data-block-id="block-02-nav">
                <ul>
                    <li><a href="#behandlinger">Behandlinger</a></li>
                    <li><a href="#tilskud">Tilskud</a></li>
                    <li><a href="#find-diaetist">Find Diætist</a></li>
                    <li><a href="#booking">Foredrag &amp; Erhverv</a></li>
                    <li><a href="#artikler">Artikler</a></li>
                    <li><a href="#faq">FAQ</a></li>
                    <li><a href="#find-diaetist" class="nav-cta"><i data-lucide="search" size="16"></i>Søg specialist</a></li>
                </ul>
            </nav>
            <button class="mobile-menu-btn" id="mobile-menu-btn" type="button" aria-label="Åbn menu">
                <span></span>
                <span></span>
                <span></span>
            </button>
        </div>
    </header>

    <div class="mobile-nav-overlay" id="mobile-nav-overlay" aria-hidden="true"></div>
    <nav class="mobile-nav-panel" id="mobile-nav-panel" aria-label="Mobil navigation">
        <button class="mobile-nav-close dd-mobile-nav-close" id="mobile-nav-close" type="button" aria-label="Luk menu"></button>
        <ul>
            <li><a href="#behandlinger">Behandlinger</a></li>
            <li><a href="#tilskud">Tilskud</a></li>
            <li><a href="#find-diaetist">Find Diætist</a></li>
            <li><a href="#booking">Foredrag &amp; Erhverv</a></li>
            <li><a href="#artikler">Artikler</a></li>
            <li><a href="#faq">FAQ</a></li>
            <li><a href="#find-diaetist" class="nav-cta"><i data-lucide="search" size="16"></i>Søg specialist</a></li>
        </ul>
    </nav>

    <!-- Hero Section -->
    <section class="hero" data-block-id="block-03-section">
        <div class="container hero-grid">
            <div class="hero-text-content">
                <div class="hero-badge">
                    <i data-lucide="shield-check" size="16"></i> Landsdækkende forening af kliniske diætister
                </div>
                <h1>Din sundhed, din <span>diætist</span></h1>
                <p>Oplev evidensbaseret, individuel ernæringsterapi, der skaber varige forandringer i dit liv. Vi tager udgangspunkt i dig, din krop og din hverdag.</p>
                <div class="hero-actions">
                    <a href="#find-diaetist" class="btn-primary">Find diætist nær dig <i data-lucide="arrow-right" size="18"></i></a>
                    <a href="#behandlinger" class="btn-secondary">Se behandlingsområder</a>
                </div>
            </div>
            <div class="hero-image-wrapper">
                <div class="hero-image-frame">
                    <img src="https://images.unsplash.com/photo-1543362906-acfc16c67564?auto=format&amp;fit=crop&amp;q=80&amp;w=800" alt="Friske, nærende råvarer tilberedt med omhu">
                    <div class="hero-image-caption">Næring i balance</div>
                </div>
                <div class="trust-box">
                    <div class="trust-stars">
                        <i data-lucide="star" fill="currentColor" size="16"></i>
                        <i data-lucide="star" fill="currentColor" size="16"></i>
                        <i data-lucide="star" fill="currentColor" size="16"></i>
                        <i data-lucide="star" fill="currentColor" size="16"></i>
                        <i data-lucide="star" fill="currentColor" size="16"></i>
                    </div>
                    <div class="trust-text">
                        Over 10.000 danskere har opnået bedre livskvalitet gennem vores specialister.
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Stats Bar -->
    <section class="stats-section" data-block-id="block-04-section">
        <div class="container stats-grid">
            <div class="stat-card">
                <h3>120+</h3>
                <p>Aktive klinikker i Danmark</p>
            </div>
            <div class="stat-card">
                <h3>100%</h3>
                <p>Sundhedsstyrelses-autoriserede</p>
            </div>
            <div class="stat-card">
                <h3>15+</h3>
                <p>Faglige specialer</p>
            </div>
            <div class="stat-card">
                <h3>85%</h3>
                <p>Får tilskud fra 'danmark'</p>
            </div>
        </div>
    </section>

    <!-- Treatments Section (10 Clinical Areas) -->
    <section id="behandlinger" class="treatments" data-block-id="block-05-section">
        <div class="container">
            <div class="section-header">
                <span class="section-tag">Behandlingsområder</span>
                <h2>Professionel diætbehandling skræddersyet til dig</h2>
                <p>Som kliniske diætister arbejder vi under Sundhedsloven. Vi tilbyder rådgivning af højeste faglige kvalitet inden for en bred vifte af ernæringsområder.</p>
            </div>

            <!-- The Grid of 10 treatments requested in the brief -->
            <div class="treatments-grid">
                <!-- 1 -->
                <div class="treatment-card" onclick="openDrawer('weight')">
                    <div>
                        <div class="treatment-icon"><i data-lucide="trending-down"></i></div>
                        <h3>Overvægt &amp; Vægttab</h3>
                        <p>Sund og holdbar vægtregulering uden restriktive kure. Vi finder en balance, der holder i din hverdag.</p>
                    </div>
                    <span class="treatment-more">Læs mere <i data-lucide="chevron-right" size="14"></i></span>
                </div>
                <!-- 2 -->
                <div class="treatment-card" onclick="openDrawer('ibs')">
                    <div>
                        <div class="treatment-icon"><i data-lucide="activity"></i></div>
                        <h3>Irriteret tyktarm (IBS)</h3>
                        <p>Ernæringsterapi mod oppustethed, smerter og uregelmæssig mave, herunder Low FODMAP diæt.</p>
                    </div>
                    <span class="treatment-more">Læs mere <i data-lucide="chevron-right" size="14"></i></span>
                </div>
                <!-- 3 -->
                <div class="treatment-card" onclick="openDrawer('diabetes')">
                    <div>
                        <div class="treatment-icon"><i data-lucide="heart-pulse"></i></div>
                        <h3>Type 2 Diabetes</h3>
                        <p>Få styr på blodsukkeret og insulinresistensen med den rette kostsammensætning uden afsavn.</p>
                    </div>
                    <span class="treatment-more">Læs mere <i data-lucide="chevron-right" size="14"></i></span>
                </div>
                <!-- 4 -->
                <div class="treatment-card" onclick="openDrawer('cardio')">
                    <div>
                        <div class="treatment-icon"><i data-lucide="heart"></i></div>
                        <h3>Hjerte-kar-sygdomme</h3>
                        <p>Koststrategier til forbedring af kolesteroltal, forebyggelse af åreforkalkning og regulering af blodtryk.</p>
                    </div>
                    <span class="treatment-more">Læs mere <i data-lucide="chevron-right" size="14"></i></span>
                </div>
                <!-- 5 -->
                <div class="treatment-card" onclick="openDrawer('ed')">
                    <div>
                        <div class="treatment-icon"><i data-lucide="smile"></i></div>
                        <h3>Spiseforstyrrelser</h3>
                        <p>Professionel støtte og genopretning af et sundt forhold til mad ved overspisning (BED), ortorexi m.m.</p>
                    </div>
                    <span class="treatment-more">Læs mere <i data-lucide="chevron-right" size="14"></i></span>
                </div>
                <!-- 6 -->
                <div class="treatment-card" onclick="openDrawer('sports')">
                    <div>
                        <div class="treatment-icon"><i data-lucide="zap"></i></div>
                        <h3>Sportsernæring</h3>
                        <p>Optimer din præstation, restitution og kropskomposition med individuelt tilpasset energi- og væskeplan.</p>
                    </div>
                    <span class="treatment-more">Læs mere <i data-lucide="chevron-right" size="14"></i></span>
                </div>
                <!-- 7 -->
                <div class="treatment-card" onclick="openDrawer('kids')">
                    <div>
                        <div class="treatment-icon"><i data-lucide="baby"></i></div>
                        <h3>Børn &amp; Unge</h3>
                        <p>Hjælp til kræsenhed, uregelmæssig vækstkurve, fødevareallergier og opbygning af sunde madvaner i familien.</p>
                    </div>
                    <span class="treatment-more">Læs mere <i data-lucide="chevron-right" size="14"></i></span>
                </div>
                <!-- 8 -->
                <div class="treatment-card" onclick="openDrawer('pcos')">
                    <div>
                        <div class="treatment-icon"><i data-lucide="sparkles"></i></div>
                        <h3>PCOS &amp; Hormonbalance</h3>
                        <p>Kostjusteringer, der balancerer insulin, mindsker symptomer og forbedrer din naturlige fertilitet.</p>
                    </div>
                    <span class="treatment-more">Læs mere <i data-lucide="chevron-right" size="14"></i></span>
                </div>
                <!-- 9 -->
                <div class="treatment-card" onclick="openDrawer('allergy')">
                    <div>
                        <div class="treatment-icon"><i data-lucide="shield-alert"></i></div>
                        <h3>Fødevareallergi</h3>
                        <p>Rådgivning ved cøliaki, laktoseintolerance og allergier, så du får dækket dine næringsbehov uden usikkerhed.</p>
                    </div>
                    <span class="treatment-more">Læs mere <i data-lucide="chevron-right" size="14"></i></span>
                </div>
                <!-- 10 -->
                <div class="treatment-card" onclick="openDrawer('underweight')">
                    <div>
                        <div class="treatment-icon"><i data-lucide="scale"></i></div>
                        <h3>Undervægt &amp; Småtspisende</h3>
                        <p>Målrettet ernæringsterapi til ældre, syge eller personer, der har brug for sund og stabil vægtøgning.</p>
                    </div>
                    <span class="treatment-more">Læs mere <i data-lucide="chevron-right" size="14"></i></span>
                </div>
            </div>
        </div>
    </section>

    <!-- Dynamic Treatment Detail Drawer -->
    <div id="drawer-overlay" class="drawer-overlay" onclick="closeDrawer()"></div>
    <div id="treatment-drawer" class="drawer">
        <button class="drawer-close" onclick="closeDrawer()">
            <i data-lucide="x" size="24"></i>
        </button>
        <div id="drawer-content">
            <!-- Content dynamically populated via JS -->
        </div>
    </div>

    <!-- Tilskud (Subsidy) Section -->
    <section id="tilskud" class="subsidy" data-block-id="block-06-section">
        <div class="container subsidy-grid">
            <div class="subsidy-text">
                <span class="section-tag">Økonomisk Støtte</span>
                <h2>Gode muligheder for offentligt tilskud</h2>
                <p>Når du konsulterer en autoriseret klinisk diætist, kan du i de fleste tilfælde få dækket en betragtelig del af udgifterne. Offentlige tilskud, sundhedsforsikringer samt Sygeforsikring "danmark" bidrager aktivt til forebyggende sundhedsydelser.</p>
                <p>Mange private sundhedssikringer dækker desuden det fulde forløb, hvis du har en henvisning fra din læge.</p>
                <div style="display: flex; gap: 1rem; align-items: center; margin-top: 2rem;">
                    <i data-lucide="info" class="accent-color" style="color: var(--accent-warm);"></i>
                    <span style="font-size: 0.95rem; font-weight: 500; color: var(--text-dark);">Kontakt din egen læge eller dit forsikringsselskab for at høre om dine specifikke muligheder.</span>
                </div>
            </div>

            <!-- Interactive Subsidy Calculator -->
            <div class="calc-card">
                <h3>Beregn dine tilskudsmuligheder</h3>
                <p style="font-size: 0.9rem; margin-bottom: 1.5rem;">Vælg din nuværende status for at se, hvor meget tilskud du kan opnå.</p>
                
                <div class="calc-group">
                    <span class="calc-label">Er du medlem af Sygeforsikring "danmark"?</span>
                    <div class="calc-options">
                        <div class="calc-option selected" onclick="selectOption('danmark', 'ja', this)">
                            <input type="radio" name="danmark" value="ja" checked="">
                            <span class="calc-option-text">Ja, Gruppe 1, 2 eller 5</span>
                        </div>
                        <div class="calc-option" onclick="selectOption('danmark', 'nej', this)">
                            <input type="radio" name="danmark" value="nej">
                            <span class="calc-option-text">Nej, jeg er ikke medlem</span>
                        </div>
                    </div>
                </div>

                <div class="calc-group">
                    <span class="calc-label">Har du en henvisning fra din praktiserende læge?</span>
                    <div class="calc-options">
                        <div class="calc-option selected" onclick="selectOption('henvisning', 'ja', this)">
                            <input type="radio" name="henvisning" value="ja" checked="">
                            <span class="calc-option-text">Ja, til kronisk sygdom (f.eks. diabetes, KOL)</span>
                        </div>
                        <div class="calc-option" onclick="selectOption('henvisning', 'nej', this)">
                            <input type="radio" name="henvisning" value="nej">
                            <span class="calc-option-text">Nej</span>
                        </div>
                    </div>
                </div>

                <div class="calc-result-box">
                    <div class="calc-result-label">Estimeret dækning af behandlingen</div>
                    <div id="calc-result" class="calc-result-value">Op til 50% dækket</div>
                    <div class="calc-result-disclaimer">Ovenstående er vejledende og forudsætter brug af en autoriseret klinisk diætist tilsluttet overenskomsten.</div>
                </div>
            </div>
        </div>
    </section>

    <!-- Interactive Directory Map & Specialty Search Section -->
    <section id="find-diaetist" class="map-section" data-block-id="block-07-section">
        <div class="container">
            <div class="section-header" style="max-width: 800px; margin-bottom: 3.5rem;">
                <span class="section-tag">Landsdækkende find-tjeneste</span>
                <h2>Find en autoriseret diætist nær dig</h2>
                <p>Brug det interaktive danmarkskort til at vælge din region, eller søg direkte på specialer for at finde den helt rette behandler til dine unikke behov.</p>
            </div>

            <div class="map-grid">
                <!-- Directory Column -->
                <div class="directory-column">
                    <div class="directory-controls">
                        <div class="search-input-wrapper">
                            <i data-lucide="search" size="20"></i>
                            <input type="text" id="dir-search" class="directory-search" placeholder="Søg på by, navn eller speciale..." oninput="filterDietitians()">
                        </div>
                        <div class="calc-label" style="font-size: 0.9rem; margin-bottom: 0.5rem;">Filtrer hurtigt efter populære specialer:</div>
                        <div class="specialty-pills" id="specialty-filters">
                            <button class="specialty-pill active" onclick="filterBySpecialty('alle', this)">Alle specialer</button>
                            <button class="specialty-pill" onclick="filterBySpecialty('Vægttab', this)">Vægttab</button>
                            <button class="specialty-pill" onclick="filterBySpecialty('IBS', this)">IBS &amp; Mave</button>
                            <button class="specialty-pill" onclick="filterBySpecialty('Diabetes', this)">Diabetes</button>
                            <button class="specialty-pill" onclick="filterBySpecialty('Sport', this)">Sport</button>
                            <button class="specialty-pill" onclick="filterBySpecialty('Børn', this)">Børn</button>
                        </div>
                    </div>

                    <div class="dietitians-list" id="dietitians-container">
                        <!-- Dynamic dietitian cards populated via JS -->
                    </div>
                </div>

                <!-- Custom Interactive SVG Denmark Map Column -->
                <div class="map-container">
                    <h3 class="map-title">
                        <i data-lucide="map-pin" style="color: var(--accent-warm);"></i>
                        Klik på en region for at filtrere
                    </h3>
                    <div class="map-svg-wrapper">
                        <svg class="denmark-map" viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg">
                            <!-- Jylland -->
                            <path class="region-path" d="M 80,80 L 150,80 L 180,120 L 210,180 L 190,260 L 160,350 L 120,440 L 90,440 L 80,350 L 70,250 L 50,180 Z" data-region="Jylland" onclick="selectRegion('Jylland')"></path>
                            <text x="110" y="220" font-family="Fraunces" font-size="16" fill="#1B3227" pointer-events="none">Jylland</text>

                            <!-- Fyn -->
                            <path class="region-path" d="M 210,360 L 260,340 L 280,380 L 240,420 L 190,390 Z" data-region="Fyn" onclick="selectRegion('Fyn')"></path>
                            <text x="230" y="380" font-family="Fraunces" font-size="14" fill="#1B3227" pointer-events="none">Fyn</text>

                            <!-- Sjælland -->
                            <path class="region-path" d="M 320,300 L 370,280 L 420,310 L 410,380 L 350,420 L 300,380 Z" data-region="Sjælland" onclick="selectRegion('Sjælland')"></path>
                            <text x="345" y="355" font-family="Fraunces" font-size="15" fill="#1B3227" pointer-events="none">Sjælland</text>

                            <!-- Bornholm -->
                            <path class="region-path" d="M 450,410 C 470,410 470,430 450,430 Z" data-region="Bornholm" onclick="selectRegion('Bornholm')"></path>
                            <text x="440" y="450" font-family="Plus Jakarta Sans" font-size="11" fill="#1B3227" pointer-events="none">Bornholm</text>
                            
                            <!-- Interactive Dots (Hovedstæder) -->
                            <circle class="map-marker" cx="170" cy="120" r="8" data-region="Jylland" onclick="selectRegion('Jylland')"></circle>
                            <circle class="map-marker" cx="240" cy="370" r="8" data-region="Fyn" onclick="selectRegion('Fyn')"></circle>
                            <circle class="map-marker" cx="390" cy="310" r="8" data-region="Sjælland" onclick="selectRegion('Sjælland')"></circle>
                        </svg>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Foredrag, Artikel & Konsulentopgaver Section -->
    <section id="booking" class="booking-section" data-block-id="block-08-section">
        <div class="container booking-grid">
            <div class="booking-text">
                <span class="section-tag" style="color: var(--accent-warm);">B2B &amp; Samarbejde</span>
                <h2>Book en ekspert til foredrag, artikler eller konsulentopgave</h2>
                <p>Søger din virksomhed, skole eller medie en faglig kapacitet inden for ernæring og sundhed? Vores autoriserede diætister formidler kompliceret videnskab i et letforståeligt og motiverende sprog.</p>
                
                <div class="booking-features">
                    <div class="booking-feat-item">
                        <div class="booking-feat-icon"><i data-lucide="presentation" size="18"></i></div>
                        <div class="booking-feat-content">
                            <h4>Inspirerende foredrag</h4>
                            <p>For virksomheder, idrætsklubber og skoler, der ønsker motiverende viden om sundhed, energi og velvære i hverdagen.</p>
                        </div>
                    </div>
                    <div class="booking-feat-item">
                        <div class="booking-feat-icon"><i data-lucide="pen-tool" size="18"></i></div>
                        <div class="booking-feat-content">
                            <h4>Fagartikler og ekspertudtalelser</h4>
                            <p>Evidensbaserede artikler til magasiner, fagblade og online medier med fokus på ernæringsfaglige emner.</p>
                        </div>
                    </div>
                    <div class="booking-feat-item">
                        <div class="booking-feat-icon"><i data-lucide="briefcase" size="18"></i></div>
                        <div class="booking-feat-content">
                            <h4>Strategisk konsulentbistand</h4>
                            <p>Fødevareudvikling, menuplanlægning til institutioner eller sundhedstjek af medarbejdere.</p>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Request Form Card -->
            <div class="booking-card">
                <h3>Send en forespørgsel</h3>
                <form id="consultant-form" onsubmit="handleFormSubmit(event)">
                    <div class="form-group">
                        <label class="form-label" for="book-name">Navn / Virksomhed</label>
                        <input type="text" id="book-name" class="form-input" required="" placeholder="F.eks. Jensen Consulting eller Maria Hansen">
                    </div>
                    <div class="form-group">
                        <label class="form-label" for="book-email">E-mailadresse</label>
                        <input type="email" id="book-email" class="form-input" required="" placeholder="F.eks. kontakt@virksomhed.dk">
                    </div>
                    <div class="form-group">
                        <label class="form-label" for="book-type">Hvad ønsker du at booke?</label>
                        <select id="book-type" class="form-select">
                            <option value="foredrag">Foredrag / Workshop</option>
                            <option value="artikel">Fagartikel / Medieudtalelse</option>
                            <option value="konsulent">Konsulentbistand</option>
                            <option value="andet">Andet samarbejde</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-label" for="book-msg">Beskriv kort din opgave / dit emne</label>
                        <textarea id="book-msg" class="form-textarea" rows="4" required="" placeholder="Skriv lidt om målgruppe, forventet dato og emne..."></textarea>
                    </div>
                    <button type="submit" class="booking-submit-btn">Send forespørgsel</button>
                </form>
            </div>
        </div>
    </section>

    <!-- Articles Section (Aktuel viden) -->
    <section id="artikler" class="articles-section" data-block-id="block-09-section">
        <div class="container">
            <div class="section-header">
                <span class="section-tag">Videnscenter</span>
                <h2>Evidensbaserede artikler &amp; råd</h2>
                <p>Vi rydder op i ernæringsjunglen og giver dig konkrete, videnskabeligt funderede artikler skrevet af praktiserende kliniske diætister.</p>
            </div>

            <div class="articles-grid">
                <!-- Article 1 -->
                <div class="article-card">
                    <div class="article-img-wrapper">
                        <img src="https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&amp;fit=crop&amp;q=80&amp;w=600" class="article-img" alt="Tarmflora ernæring">
                        <span class="article-tag">Tarmsundhed</span>
                    </div>
                    <div class="article-content">
                        <div class="article-meta">
                            <span><i data-lucide="user" size="14"></i> Signe Hansen</span>
                            <span><i data-lucide="calendar" size="14"></i> 14. Okt 2024</span>
                        </div>
                        <h3 class="article-title"><a href="#">Få ro i maven med den rette kost ved IBS</a></h3>
                        <p class="article-excerpt">Hver 10. dansker lider af irriteret tyktarm. Se de 5 mest effektive kostråd til at lindre oppustethed og mavekramper uden dyre kosttilskud.</p>
                        <a href="#" class="article-link">Læs artiklen <i data-lucide="arrow-right" size="14"></i></a>
                    </div>
                </div>

                <!-- Article 2 -->
                <div class="article-card">
                    <div class="article-img-wrapper">
                        <img src="https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&amp;fit=crop&amp;q=80&amp;w=600" class="article-img" alt="Sund mad og kosttilskud">
                        <span class="article-tag">Vægttab</span>
                    </div>
                    <div class="article-content">
                        <div class="article-meta">
                            <span><i data-lucide="user" size="14"></i> Morten Krogh</span>
                            <span><i data-lucide="calendar" size="14"></i> 28. Sep 2024</span>
                        </div>
                        <h3 class="article-title"><a href="#">Hvorfor restriktive kure modarbejder dit vægttab</a></h3>
                        <p class="article-excerpt">Hjerne og krop reagerer på hård kalorierestriktion som hungersnød. Lær hvorfor et varigt vægttab handler om tilføjelser frem for restriktioner.</p>
                        <a href="#" class="article-link">Læs artiklen <i data-lucide="arrow-right" size="14"></i></a>
                    </div>
                </div>

                <!-- Article 3 -->
                <div class="article-card">
                    <div class="article-img-wrapper">
                        <img src="https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&amp;fit=crop&amp;q=80&amp;w=600" class="article-img" alt="Aktiv livsstil og ernæring">
                        <span class="article-tag">Energi &amp; Sport</span>
                    </div>
                    <div class="article-content">
                        <div class="article-meta">
                            <span><i data-lucide="user" size="14"></i> Camilla Vestergaard</span>
                            <span><i data-lucide="calendar" size="14"></i> 11. Sep 2024</span>
                        </div>
                        <h3 class="article-title"><a href="#">Hvad skal du spise før og efter træning?</a></h3>
                        <p class="article-excerpt">Kostens timing har enorm indflydelse på din træningseffekt og restitution. Få den ultimative guide til proteiner og kulhydrater i praksis.</p>
                        <a href="#" class="article-link">Læs artiklen <i data-lucide="arrow-right" size="14"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- FAQ Section -->
    <section id="faq" class="faq-section" data-block-id="block-10-section">
        <div class="container faq-grid">
            <div>
                <span class="section-tag">Spørgsmål &amp; Svar</span>
                <h2 style="font-size: 3rem; margin-bottom: 1.5rem;">Ofte stillede spørgsmål</h2>
                <p>Har du spørgsmål til, hvordan et forløb fungerer, priser eller henvisninger? Her finder du svar på de mest almindelige spørgsmål.</p>
                <div style="margin-top: 2rem;">
                    <a href="#find-diaetist" class="btn-primary">Kontakt os direkte</a>
                </div>
            </div>

            <!-- Accordion -->
            <div class="faq-accordion">
                <div class="faq-item" onclick="toggleFaq(this)">
                    <div class="faq-header">
                        <h3>Hvad er forskellen på en klinisk diætist og en kostvejleder?</h3>
                        <div class="faq-icon-box"><i data-lucide="chevron-down" size="20"></i></div>
                    </div>
                    <div class="faq-content">
                        <p>"Klinisk diætist" er en beskyttet titel, der kræver en autoriseret professionsbachelor i ernæring og sundhed godkendt af Sundhedsstyrelsen. Vi uddannes i klinisk behandling af sygdomme via kosten. En "kostvejleder" er en ubeskyttet titel, som alle kan kalde sig efter korte, uregulerede kurser.</p>
                    </div>
                </div>

                <div class="faq-item" onclick="toggleFaq(this)">
                    <div class="faq-header">
                        <h3>Kan jeg få tilskud, hvis jeg ikke fejler noget kronisk?</h3>
                        <div class="faq-icon-box"><i data-lucide="chevron-down" size="20"></i></div>
                    </div>
                    <div class="faq-content">
                        <p>Ja. Sygeforsikring "danmark" giver tilskud til vægttab, kostvejledning og forebyggelse, også uden en diagnose eller lægehenvisning. Mange private sundhedsforsikringer dækker ligeledes forebyggende forløb uden krav om kronisk sygdom.</p>
                    </div>
                </div>

                <div class="faq-item" onclick="toggleFaq(this)">
                    <div class="faq-header">
                        <h3>Hvor mange samtaler skal jeg forvente i et forløb?</h3>
                        <div class="faq-icon-box"><i data-lucide="chevron-down" size="20"></i></div>
                    </div>
                    <div class="faq-content">
                        <p>Et typisk forløb starter med en dybdegående første konsultation (60-75 min.). Derefter følger typisk 3-5 opfølgende samtaler (30-45 min.) fordelt over 3-6 måneder for at sikre implementering og langsigtede, sunde vaner i din dagligdag.</p>
                    </div>
                </div>

                <div class="faq-item" onclick="toggleFaq(this)">
                    <div class="faq-header">
                        <h3>Kan diætisten hjælpe hele familien, herunder børn?</h3>
                        <div class="faq-icon-box"><i data-lucide="chevron-down" size="20"></i></div>
                    </div>
                    <div class="faq-content">
                        <p>Ja, vi har specialister, der arbejder specifikt med børn, unge og familier. Vi fokuserer på at gøre måltiderne hyggelige og fjerne det pres, der kan opstå omkring maden ved f.eks. kræsenhed eller overvægt hos børn.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Footer -->
    <footer data-block-id="block-11-footer">
        <div class="container">
            <div class="footer-grid">
                <div>
                    <a href="#" class="footer-logo">
                        <img class="dd-brand-logo" alt="Diætist Danmark" />
                    </a>
                    <p class="footer-desc">Din trygge indgang til professionel ernæringsterapi. Vi forener videnskabelig ekspertise med menneskelig forståelse.</p>
                </div>
                <div class="footer-col">
                    <h4>Behandlinger</h4>
                    <ul>
                        <li><a href="#behandlinger" onclick="openDrawer('weight')">Overvægt &amp; vægttab</a></li>
                        <li><a href="#behandlinger" onclick="openDrawer('ibs')">Irriteret tyktarm (IBS)</a></li>
                        <li><a href="#behandlinger" onclick="openDrawer('diabetes')">Type 2 Diabetes</a></li>
                        <li><a href="#behandlinger" onclick="openDrawer('ed')">Spiseforstyrrelser</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>B2B / Samarbejde</h4>
                    <ul>
                        <li><a href="#booking">Book foredrag</a></li>
                        <li><a href="#booking">Skriv en fagartikel</a></li>
                        <li><a href="#booking">Konsulentopgaver</a></li>
                        <li><a href="#find-diaetist">Find en ekspert</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Kontakt &amp; info</h4>
                    <ul>
                        <li><a href="#tilskud">Tilskudsordninger</a></li>
                        <li><a href="#faq">Ofte stillede spørgsmål</a></li>
                        <li><a href="mailto:info@diaetistdanmark.dk">info@diaetistdanmark.dk</a></li>
                        <li><a href="tel:+4570000000">+45 70 00 00 00</a></li>
                    </ul>
                </div>
            </div>
            <div class="footer-bottom">
                <div>© 2024 Diætist Danmark. Alle rettigheder forbeholdes.</div>
                <div class="footer-bottom-links">
                    <a href="#">Privatlivspolitik</a>
                    <a href="#">Cookieindstillinger</a>
                    <a href="#">Vilkår for brug</a>
                </div>
            </div>
        </div>
    </footer>

    <!-- Toast Notification System -->
    <div id="toast" class="toast">
        <i data-lucide="check-circle" style="color: var(--accent-warm);"></i>
        <span id="toast-message">Tak for din besked! Vi vender hurtigt tilbage.</span>
    </div>

    <!-- Interactive JS Functionality -->
</div>
  <?php wp_footer(); ?>
</body>
</html>
